variables:
  CONTAINER_NAME: mytuur-api
  IMAGE_NAME: bcodercastle/mytuur-api
  IMAGE_TAG: latest
  PORT: 3023

stages:
  - build
  - deploy

docker-build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - dev

deploy-build:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no
      root@199.192.21.220 " docker login -u $DOCKER_USERNAME -p $DOCKER_PASS &&
      docker ps -aq --filter name=$CONTAINER_NAME | xargs -r docker stop | xargs -r docker rm && docker
      run -d -p $PORT:$PORT --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG"
