variables:
    IMAGE_NAME: bcodercastle/mytuur-api
    IMAGE_TAG: latest

stages:
    - build

docker-build:
    stage: build
    image: docker:24.0.7-cli
    services:
        - docker:24.0.7-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script: 
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
        - echo "Built Docker Image Successfully!"
    only:
        - dev