variables:
    IMAGE_NAME: bcodercastle/mytuur-api
    IMAGE_TAG: latest

stages:
    - build

docker-build:
    stage: build
    image: docker:stable
    services:
    - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script: 
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:latest
        - echo "Built Docker Image Successfully!"
    only:
        - dev